### ISSUE TITLE
 http://vijayan.ca/blog/2012/02/21/javascript-type-model/ is down

### ISSUE THREAD

**Issue by TianCNCA** [stevekwan/experiments#5]
Can you please provide a copy of that article? Thanks very much!

**Comment by stevekwan** [comment]
Sure thing, I'll find an archived link.

**Comment by stevekwan** [comment]
The link is:
http://web.archive.org/web/20150211073056/http://vijayan.ca/blog/2012/02/21/javascript-type-model

I'll change the link in the document itself.
